name: CI

on: [push, pull_request]

jobs:
  format:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build

      - run: docker-compose -f tests/docker-compose.yml run -d
      - run: sleep 60

      - uses: actions-rs/cargo@v1
        with:
          command: test

        env:
          DATABASE_URL: mysql://root:root@localhost:3306/eludris

  clippy:
    name: Clippy; Destroyer of Realities.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - run: docker-compose -f tests/docker-compose.yml run -d
      - run: sleep 60

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

        env:
          DATABASE_URL: mysql://root:root@localhost:3306/eludris
