name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Formattin

    # Do not run on PRs from the same repo, since `push` already handles them.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  test:
    name: Tests

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: docker-compose -f tests/docker-compose.yml up -d

      # Build crates while Kafka starts.
      - uses: actions-rs/cargo@v1
        with:
          command: build

      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUST_LOG: "trace"
          REDIS_URL: "redis://127.0.0.1:6379"

  clippy:
    name: Clippy; Destroyer of Realities.

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - run: docker-compose -f tests/docker-compose.yml up -d

      # Build crates while Kafka starts.
      - uses: actions-rs/cargo@v1
        with:
          command: build

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
